---
version: "3.4"
services:
  explorer:
    build:
      context: .
      args:
        ENVIRONMENT: deployment
    ports:
      - 80:8080
    environment:
      # - DB_HOSTNAME=host.docker.internal
      - DB_HOSTNAME=postgres
      - DB_USERNAME=opendatacube
      - DB_PASSWORD=opendatacubepassword
      - DB_DATABASE=opendatacube
      - DB_PORT=5432
      - FLASK_ENV=development
      - FLASK_APP=cubedash
      - FLASK_DEBUG=1
      - CUBEDASH_DEFAULT_TIMEZONE=Australia/Darwin
      # - VIRTUAL_HOST=datacube.explorer
    depends_on:
      - postgres

  postgres:
    image: postgis/postgis:13-3.4
    hostname: postgres
    environment:
      - POSTGRES_DB=opendatacube
      - POSTGRES_PASSWORD=opendatacubepassword
      - POSTGRES_USER=opendatacube
    ports:
      - 5432:5432
    restart: always
    healthcheck:
      test: ["CMD", "pg_isready", "-h", "postgres", "-q", "-d", "opendatacube", "-U", "opendatacube"]
      timeout: 45s
      interval: 10s
      retries: 10

  # Needed for testing HTTPS
  # nginx-proxy:
  #   image: jwilder/nginx-proxy
  #   container_name: nginx-proxy
  #   ports:
  #     - "5000:80"
  #     - "443:443"
  #   volumes:
  #     - /var/run/docker.sock:/tmp/docker.sock:ro
  #     - ./certs:/etc/nginx/certs
  #   depends_on:
  #     - explorer
