---
name: Docker

on:
  workflow_dispatch:

  push:
    branches:
      - develop
    paths:
      - "**"

  release:
    types: [created, edited, published]

env:
  IMAGE_NAME: opendatacube/explorer

jobs:
  docker:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/develop' || github.event_name == 'release'

    steps:
      - name: Checkout git
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Get unstable git tag
        run: >
          echo "UNSTABLE_TAG=$(git describe --tags)" >> $GITHUB_ENV

      - name: Log the unstable tag
        run: echo $UNSTABLE_TAG

      - name: Build and Push unstable + latest Docker image tag
        if: github.event_name != 'release'
        uses: whoan/docker-build-with-cache-action@v4
        with:
          image_name: ${{ env.IMAGE_NAME }}
          username: gadockersvc
          image_tag: ${{ env.UNSTABLE_TAG }},latest
          password: "${{ secrets.DockerPassword }}"
          build_extra_args: "--build-arg=ENVIRONMENT=deployment"

      # This section is for releases
      - name: Get tag for this build if it exists
        if: github.event_name == 'release'
        run: >
          echo "RELEASE=$(git describe --abbrev=0 --tags)" >> $GITHUB_ENV

      - name: Log the tag
        run: echo $RELEASE

      - name: Build and Push release if we have a tag
        uses: whoan/docker-build-with-cache-action@v4
        if: github.event_name == 'release'
        with:
          image_name: ${{ env.IMAGE_NAME }}
          image_tag: ${{ env.RELEASE }}
          username: gadockersvc
          password: "${{ secrets.DockerPassword }}"
          build_extra_args: "--build-arg=ENVIRONMENT=deployment"

      - name: Update Docker Hub Description
        uses: peter-evans/dockerhub-description@v2
        with:
          username: gadockersvc
          password: ${{ secrets.DockerPassword }}
          repository: ${{ env.IMAGE_NAME }}
          readme-filepath: README.md
          short-description: Open Data Cube Explorer Image

      - name: Notify Slack for Failures
        uses: rtCamp/action-slack-notify@v2.2.0
        if: failure()
        env:
          SLACK_CHANNEL: explorer-alerts
          SLACK_ICON: "https://github.com/docker.png?size=48"
          SLACK_COLOR: "#482de1"
          SLACK_MESSAGE: ""
          SLACK_TITLE: Docker failure
          SLACK_USERNAME: Explorer Docker
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}

  publish_pypi:
    runs-on: ubuntu-latest
    if: |
      github.event_name == 'release'
      && github.event.release.action == 'published'

    steps:
      - name: Build Packages
        run: |
          cat <<EOF | docker run --rm -i  \
                    -v $(pwd):/code \
                    -e SKIP_DB=yes \
                    ${{ env.IMAGE_NAME }} bash -
          python setup.py bdist_wheel sdist
          ls -lh ./dist/
          if hash twine 2> /dev/null ; then
            twine check ./dist/*
          else
            echo "WARNING: twine is missing from the docker!"
          fi
          EOF

      - name: Publish to PyPi
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          password: ${{ secrets.PyPiToken }}
